[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "postgresql"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --no-input"]

[start]
cmd = "python manage.py migrate && gunicorn config.wsgi:application"
